coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: null
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: no
ignore:
  - ".github/**"
  - ".dev/**"
  - "dashboard/**"
  - "website/**"
  - "ci/**"
  - "**/*_test.go"
  - "**/*_test.go"
  - "**/vendor/**"
  - "**/testdata/*"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*_mock.go"