---
project_name: teredix
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["ghcr.io/shaharia-lab/teredix:{{ .Version }}"]
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/shaharia-lab/teredix
      - --label=org.opencontainers.image.source=https://github.com/shaharia-lab/teredix
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
nfpms:
  - maintainer: Shaharia Lab OÜ <hello@shaharialab.com>
    description: Teredix discover and tech resource and generate resource graph
    homepage: https://github.com/shaharia-lab/teredix
    license: MIT
    formats:
      - deb
      - rpm
      - apk