package scanner

import (
	"teredix/pkg/resource"
	"testing"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/stretchr/testify/mock"
)

// AWSS3Client is an autogenerated mock type for the AWSS3Client type
type AWSS3ClientMock struct {
	mock.Mock
}

// GetBucketTagging provides a mock function with given fields: bucketTaggingInput
func (_m *AWSS3ClientMock) GetBucketTagging(bucketTaggingInput *s3.GetBucketTaggingInput) (*s3.GetBucketTaggingOutput, error) {
	ret := _m.Called(bucketTaggingInput)

	var r0 *s3.GetBucketTaggingOutput
	if rf, ok := ret.Get(0).(func(*s3.GetBucketTaggingInput) *s3.GetBucketTaggingOutput); ok {
		r0 = rf(bucketTaggingInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetBucketTaggingOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*s3.GetBucketTaggingInput) error); ok {
		r1 = rf(bucketTaggingInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBuckets provides a mock function with given fields: listBucketInput
func (_m *AWSS3ClientMock) ListBuckets(listBucketInput *s3.ListBucketsInput) (*s3.ListBucketsOutput, error) {
	ret := _m.Called(listBucketInput)

	var r0 *s3.ListBucketsOutput
	if rf, ok := ret.Get(0).(func(*s3.ListBucketsInput) *s3.ListBucketsOutput); ok {
		r0 = rf(listBucketInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListBucketsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*s3.ListBucketsInput) error); ok {
		r1 = rf(listBucketInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestAWSS3_Scan(t *testing.T) {
	testCases := []struct {
		name          string
		buckets       []*s3.Bucket
		tags          []*s3.Tag
		expectedError error
		expectedCount int
	}{
		{
			name: "successfully list buckets and map resources",
			buckets: []*s3.Bucket{
				{Name: aws.String("bucket1")},
				{Name: aws.String("bucket2")},
			},
			tags: []*s3.Tag{
				{Key: aws.String("Environment"), Value: aws.String("Production")},
			},
			expectedError: nil,
			expectedCount: 2,
		},
	}
	for _, tt := range testCases {
		t.Run(tt.name, func(t *testing.T) {
			s3ClientMock := new(AWSS3ClientMock)
			s3ClientMock.On("ListBuckets", mock.Anything).Return(&s3.ListBucketsOutput{Buckets: tt.buckets}, nil)
			s3ClientMock.On("GetBucketTagging", mock.Anything).Return(&s3.GetBucketTaggingOutput{TagSet: tt.tags}, nil)

			resourceChannel := make(chan resource.Resource, len(tt.buckets))
			var res []resource.Resource

			go func() {
				// Create an FsScanner for the temporary directory and scan it
				a := NewAWSS3("source-name", "us-east-1", s3ClientMock)
				a.Scan(resourceChannel)

				close(resourceChannel)
			}()

			for r := range resourceChannel {
				res = append(res, r)
			}

			if len(res) != tt.expectedCount {
				t.Errorf("unexpected number of resources: got %d, want %d", len(res), tt.expectedCount)
			}
		})
	}
}
