// Package scanner scans targets
package scanner

import (
	"teredix/pkg/resource"

	"github.com/stretchr/testify/mock"
)

// Mock is an autogenerated mock type for the ScannerMock type
type Mock struct {
	mock.Mock
}

// Scan provides a mock function with given fields:
func (_m *Mock) Scan() []resource.Resource {
	ret := _m.Called()

	var r0 []resource.Resource
	if rf, ok := ret.Get(0).(func() []resource.Resource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.Resource)
		}
	}

	return r0
}

// ScanSource provides a mock function with given fields: resourceChannel
func (_m *Mock) ScanSource(resourceChannel chan resource.Resource) error {
	ret := _m.Called(resourceChannel)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan resource.Resource) error); ok {
		r0 = rf(resourceChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
