package scanner

import (
	"github.com/stretchr/testify/mock"
	"teredix/pkg/resource"
)

// ScannerMock is an autogenerated mock type for the ScannerMock type
type ScannerMock struct {
	mock.Mock
}

// Scan provides a mock function with given fields:
func (_m *ScannerMock) Scan() []resource.Resource {
	ret := _m.Called()

	var r0 []resource.Resource
	if rf, ok := ret.Get(0).(func() []resource.Resource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.Resource)
		}
	}

	return r0
}
