{
 "title": "TerediX Resources",
 "description": "Resource related dashboard for TerediX",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(teredix_total_resource,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(teredix_total_resource,job)"
    }
   },
   { "name": "scanner_name", "label": "Scanner name", "query": { "query": "label_values(scanner_name)" } },
   { "name": "scanner_kind", "label": "Scanner kind", "query": { "query": "label_values(scanner_kind)" } },
   { "name": "metadata_key", "label": "Metadata Keys", "query": { "query": "label_values(metadata_key)" } },
   {
    "name": "metadata_value",
    "label": "Metadata value",
    "query": {
     "query": "label_values(teredix_total_resource_by_metadata_key_value,metadata_value)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "description": "Total Resources",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teredix_total_resource{instance=~\"$instance\", job=~\"$job\",scanner_kind=~\"$scanner_kind\", scanner_name=~\"$scanner_name\"})"
    }
   ]
  },
  {
   "title": "Total Resources by Kind",
   "type": "piechart",
   "description": "Total Resources by Kind",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teredix_total_resource{instance=~\"$instance\", job=~\"$job\",scanner_kind=~\"$scanner_kind\", scanner_name=~\"$scanner_name\"}) by (scanner_kind)"
    }
   ]
  },
  {
   "title": "Total Resource by Meta Data Key",
   "type": "timeseries",
   "description": "Total Resource by Meta Data Key",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_total_resource_by_metadata_key{instance=~\"$instance\", job=~\"$job\",scanner_kind=~\"$scanner_kind\", scanner_name=~\"$scanner_name\", metadata_key=~\"$metadata_key\"}) by (metadata_key)"
    }
   ]
  },
  {
   "title": "Total Resources by Scanner",
   "type": "piechart",
   "description": "Total Resources by Scanner",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(teredix_total_resource{instance=~\"$instance\", job=~\"$job\",scanner_kind=~\"$scanner_kind\", scanner_name=~\"$scanner_name\"}) by (scanner_name)"
    }
   ]
  },
  {
   "title": "Resource Count Changes over Time",
   "type": "timeseries",
   "description": "Resource Count Changes over Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(teredix_total_resource{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Resource by Meta Data Value",
   "type": "timeseries",
   "description": "Total Resource by Meta Data Value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_total_resource_by_metadata_key_value{instance=~\"$instance\", job=~\"$job\",scanner_kind=~\"$scanner_kind\", scanner_name=~\"$scanner_name\", metadata_key=~\"$metadata_key\", metadata_value=~\"$metadata_value\"}) by (metadata_value)"
    }
   ]
  }
 ]
}