{
 "title": "TerediX General",
 "description": "TerediX general dashboard. Managed by https://github.com/shaharia-lab/terediX",
 "tags": [
  "terediX",
  "tech-resource-discovery",
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(teredix_scheduler_start_count,instance)"
    }
   },
   { "name": "scanner_name", "label": "Scanner Name", "query": { "query": "label_values(scanner_name)" } },
   { "name": "scanner_kind", "label": "Scanner Kind", "query": { "query": "label_values(scanner_kind)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(teredix_scheduler_start_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resource Discovered",
   "type": "timeseries",
   "description": "Total Resource Discovered",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "teredix_resource_discovered_by_scanner{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Count by Job Status",
   "type": "timeseries",
   "description": "Total Count by Job Status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_scanner_job_status_count{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}) by (scanner_name, scanner_kind, status)"
    }
   ]
  },
  {
   "title": "Scan Duration per Scanner",
   "type": "timeseries",
   "description": "Average Scan Duration per Scanner",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "teredix_scan_duration_seconds{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Batch Persisting Latency / Duration",
   "type": "timeseries",
   "description": "Batch Persisting Latency / Duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "teredix_storage_batch_persisting_latency_in_ms{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Scanner in MB",
   "type": "timeseries",
   "description": "Memory Usage Per Scanner in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "teredix_memory_usage_by_scanner_in_mb{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Scanner in KB",
   "type": "timeseries",
   "description": "Memory Usage Per Scanner in KB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "teredix_memory_usage_by_scanner_in_kb{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Scanner in Bytes",
   "type": "timeseries",
   "description": "Memory Usage Per Scanner in Bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "teredix_memory_usage_by_scanner_in_bytes{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Scheduler Start Count",
   "type": "timeseries",
   "description": "Scheduler Start Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "teredix_scheduler_start_count{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Scanner Build",
   "type": "timeseries",
   "description": "Total Scanner Created over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "teredix_scanner_build_total{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Scanner Job Added To Queue",
   "type": "timeseries",
   "description": "Scanner Job Added To Queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_scanner_job_added_to_queue{scanner_name=~\"$scanner_name\", scanner_kind=~\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}) by (scanner_name, scanner_kind, result)"
    }
   ]
  },
  {
   "title": "Process Error Count by Failure Type",
   "type": "timeseries",
   "description": "Process Error Count by Failure Type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_process_error_count{instance=~\"$instance\", job=~\"$job\"}) by (failure_type)"
    }
   ]
  },
  {
   "title": "Scanner Built by Kind",
   "type": "timeseries",
   "description": "Scanner Built by Kind",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(teredix_scanner_build_by_kind{scanner_kind=\"$scanner_kind\", instance=~\"$instance\", job=~\"$job\"}) by (scanner_kind)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}