---
# See https://golangci-lint.run/usage/configuration/#config-file for more information
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - goimports
  fast: false
linters-settings:
  gofmt:
    simplify: false
  jscpd:
    severity: "warning"
    threshold: 10
    min-lines: 5
    exclude:
      - "**/*_test.go"
      - "**/*_mock.go"
issues:
  exclude-use-default: false