package scanner

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/stretchr/testify/mock"
)

// AWSS3Client is an autogenerated mock type for the AWSS3Client type
type AWSS3ClientMock struct {
	mock.Mock
}

// GetBucketTagging provides a mock function with given fields: bucketTaggingInput
func (_m *AWSS3ClientMock) GetBucketTagging(bucketTaggingInput *s3.GetBucketTaggingInput) (*s3.GetBucketTaggingOutput, error) {
	ret := _m.Called(bucketTaggingInput)

	var r0 *s3.GetBucketTaggingOutput
	if rf, ok := ret.Get(0).(func(*s3.GetBucketTaggingInput) *s3.GetBucketTaggingOutput); ok {
		r0 = rf(bucketTaggingInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetBucketTaggingOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*s3.GetBucketTaggingInput) error); ok {
		r1 = rf(bucketTaggingInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBuckets provides a mock function with given fields: listBucketInput
func (_m *AWSS3ClientMock) ListBuckets(listBucketInput *s3.ListBucketsInput) (*s3.ListBucketsOutput, error) {
	ret := _m.Called(listBucketInput)

	var r0 *s3.ListBucketsOutput
	if rf, ok := ret.Get(0).(func(*s3.ListBucketsInput) *s3.ListBucketsOutput); ok {
		r0 = rf(listBucketInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListBucketsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*s3.ListBucketsInput) error); ok {
		r1 = rf(listBucketInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestAWSS3_Scan(t *testing.T) {
	testCases := []struct {
		name                  string
		sourceFields          []string
		buckets               []*s3.Bucket
		tags                  []*s3.Tag
		expectedTotalResource int
		expectedMetaDataKeys  []string
	}{
		{
			name: "successfully list buckets and map resources",
			sourceFields: []string{
				s3fieldRegion,
				s3fieldARN,
				s3fieldBucketName,
			},
			buckets: []*s3.Bucket{
				{Name: aws.String("bucket1")},
				{Name: aws.String("bucket2")},
			},
			tags: []*s3.Tag{
				{Key: aws.String("tag1"), Value: aws.String("value1")},
			},
			expectedTotalResource: 2,
			expectedMetaDataKeys:  []string{s3fieldRegion, s3fieldARN, s3fieldBucketName, "tag_tag1"},
		},
	}
	for _, tt := range testCases {
		t.Run(tt.name, func(t *testing.T) {
			s3ClientMock := new(AWSS3ClientMock)
			s3ClientMock.On("ListBuckets", mock.Anything).Return(&s3.ListBucketsOutput{Buckets: tt.buckets}, nil)
			s3ClientMock.On("GetBucketTagging", mock.Anything).Return(&s3.GetBucketTaggingOutput{TagSet: tt.tags}, nil)

			resources := RunScannerForTests(NewAWSS3("source-name", "us-east-1", s3ClientMock, []string{}))

			assert.Equal(t, tt.expectedTotalResource, len(resources))
		})
	}
}
