// Package scanner scans targets
package scanner

import (
	"github.com/shaharia-lab/teredix/pkg/resource"

	"github.com/stretchr/testify/mock"
)

// Mock is an autogenerated mock type for the ScannerMock type
type Mock struct {
	mock.Mock
}

// Scan provides a mock function with given fields: resourceChannel, nextResourceVersion
func (_m *Mock) Scan(resourceChannel chan resource.Resource, nextResourceVersion int) error {
	ret := _m.Called(resourceChannel, nextResourceVersion)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan resource.Resource, int) error); ok {
		r0 = rf(resourceChannel, nextResourceVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetKind provides a mock function with given fields:
func (_m *Mock) GetKind() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
