{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teredix.fullname" $ }}-{{ $service.name }}
  {{- if $service.annotations }}
  annotations:
    {{- toYaml $service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "teredix.labels" $ | nindent 4 }}
spec:
  type: {{ $service.type }}
  ports:
    - port: {{ $service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "teredix.selectorLabels" $ | nindent 4 }}
---
{{- end }}