# ref: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: [ master ]
    paths:
      - '.dev/**'
      - '.github/workflows/dev_docker_image_publish.yaml'
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - '.dev/**'
      - '.github/workflows/dev_docker_image_publish.yaml'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./.dev/Dockerfile
          context: ./.dev
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.repository_owner }}/teredix:dev
          labels: ${{ steps.meta.outputs.labels }}