name: Test & Linting Charts

on:
    push:
      branches: [ master ]
      paths:
        - 'helm-chart/**'
    pull_request:
      branches: [ master ]
      paths:
        - 'helm-chart/**'
      types: [opened, synchronize, reopened]

jobs:
  lint-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
        CT_CHART_DIRS: helm-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Prepare kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace teredix-testing

          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install postgresql bitnami/postgresql --namespace "teredix-testing" \
            --set auth.username="app" \
            --set auth.password="pass" \
            --set auth.database="app"

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} \
            --namespace teredix-testing --debug \
            --helm-extra-set-args "-f helm-chart/teredix/values.yaml -f helm-chart/teredix_values_ci.yaml --timeout 180s"