name: Go Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v2

      - name: Run General Linting
        uses: docker://ghcr.io/github/super-linter:slim-v4.8.5
        env:
          VALIDATE_ALL_CODEBASE: false

      - name: Build
        run: make build

      - name: Test
        run: make test
